name: Publish to npm

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository
              uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "19"
                  registry-url: "https://registry.npmjs.org"

            - name: Install dependencies using Yarn
              run: yarn install

            - name: Commit changes to yarn.lock if any
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add yarn.lock
                  git commit -m "Update yarn.lock" || echo "No changes to commit"

            - name: Check for uncommitted changes
              run: |
                  git diff --exit-code || (echo "Uncommitted changes found. Please ensure the working directory is clean." && exit 1)

            - name: Update version
              run: npm version patch

            - name: Push updated version and yarn.lock
              run: |
                  git push origin main

            - name: Build lib
              run: npm run build

            - name: Build bin
              run: npm run cmd:build

            - name: Publish to npm
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
