name: Publish to npm

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository
              uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "19"
                  registry-url: "https://registry.npmjs.org"

            - name: Install dependencies using Yarn
              run: yarn install

            - name: Build lib
              run: npm run build

            - name: Build bin
              run: npm run cmd:build

            - name: Publish to npm
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
